[package]
name = "sycamore-state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inner_macros = { path = "./inner_macros" }
inner = { path = "./inner" }

sycamore = { version = "0.9.0-beta.1", features = [
    "suspense",
], git = "https://github.com/sycamore-rs/sycamore.git" }
