[package]
name = "inner"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = { version = "0.9.0-beta.1", features = [
    "suspense",
], git = "https://github.com/sycamore-rs/sycamore.git" }
